import type { Variable } from '@kata/core';

export const MUSIC_P1_VARIABLES: Variable[] = [
  { id: 'V1', name: 'Interval Discrimination', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Identify the interval between two pitches.',
    normativeRange: { lower: 70, upper: 95 } },
  { id: 'V2', name: 'Chord Quality Recognition', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Identify chord qualities (major, minor, seventh, etc.).',
    normativeRange: { lower: 65, upper: 90 } },
  { id: 'V3', name: 'Tonal Centre Perception', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Identify the tonal centre (key) of a passage.',
    normativeRange: { lower: 65, upper: 90 } },
  { id: 'V4', name: 'Pitch Class Recognition', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Identify individual pitch classes by name.',
    normativeRange: { lower: 70, upper: 95 } },
  { id: 'V5', name: 'Melodic Contour Perception', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Describe the shape of a melody (rising, falling, arch, etc.).',
    normativeRange: { lower: 70, upper: 90 } },
  { id: 'V6', name: 'Simultaneous Pitch Fusion', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Perceive a chord as a unified colour vs separate pitches.',
    normativeRange: { lower: 70, upper: 90 } },
  { id: 'V7', name: 'Frequency Masking Detection', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Detect when one tone masks another.',
    normativeRange: { lower: 70, upper: 90 } },
  { id: 'V8', name: 'Phrase Boundary Perception', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Identify phrase boundaries in a melodic passage.',
    normativeRange: { lower: 70, upper: 90 } },
  { id: 'V9', name: 'Microtonal Deviation Detection', unit: 'cents', lowerIsBetter: false,
    definition: 'Detect small deviations from intended pitch.',
    normativeRange: { lower: 70, upper: 80 } },
  { id: 'V10', name: 'Interval Inversion Recognition', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Identify an interval by its inversion.',
    normativeRange: { lower: 70, upper: 95 } },
  { id: 'V11', name: 'Enharmonic Equivalence Recognition', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Recognize that two differently-named pitches sound identical.',
    normativeRange: { lower: 70, upper: 95 } },
  { id: 'V12', name: 'Absolute Pitch Class Identification', unit: '% accuracy', lowerIsBetter: false,
    definition: 'Name a pitch class without a reference.',
    normativeRange: { lower: 70, upper: 95 } },
];