import type { Variable } from '@kata/core';

export const P2_VARIABLES: Variable[] = [
  { id: 'V1', name: 'Ratio Perception', unit: '% error', lowerIsBetter: true,
    definition: 'Accuracy estimating the ratio A:B between two extents.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V2', name: 'Reference Unit Establishment', unit: '% error', lowerIsBetter: true,
    definition: 'Establish and maintain a consistent reference unit.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V3', name: 'Comparison Direction Bias', unit: '% error', lowerIsBetter: true,
    definition: 'Judge A:B and B:A consistently.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V4', name: 'Magnitude Effect', unit: '% error', lowerIsBetter: true,
    definition: 'Judge extreme ratios without underestimation.',
    normativeRange: { lower: 0, upper: 10 } },
  { id: 'V5', name: 'Distance Extraction', unit: '% error', lowerIsBetter: true,
    definition: 'Extract and reproduce a distance between two points.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V6', name: 'Part-Whole Integration', unit: '% error', lowerIsBetter: true,
    definition: 'Judge a part as a fraction of the whole.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V7', name: 'Cross-Dimension Comparison', unit: '% error', lowerIsBetter: true,
    definition: 'Judge H:W and other cross-dimension ratios.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V8', name: 'Memory Decay of Ratio', unit: 'seconds', lowerIsBetter: false,
    definition: 'Recall a ratio after a delay.',
    normativeRange: { lower: 3, upper: 10 } },
  { id: 'V9', name: 'Context Interference', unit: '% error', lowerIsBetter: true,
    definition: 'Judge a ratio despite distracting context.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V10', name: 'Scale Invariance', unit: '% error', lowerIsBetter: true,
    definition: 'Judge the same ratio at different scales.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V11', name: 'Position Extraction', unit: '% error', lowerIsBetter: true,
    definition: 'Find midpoints, thirds, quarters, and golden-section points.',
    normativeRange: { lower: 0, upper: 5 } },
  { id: 'V12', name: 'Symmetry Ratio Detection', unit: '% error', lowerIsBetter: true,
    definition: 'Detect ratio-based symmetry in shapes.',
    normativeRange: { lower: 0, upper: 5 } },
];