import type { Variable } from '@kata/core';

export const P3_VARIABLES: Variable[] = [
  {
    id: 'V1',
    name: 'JND',
    definition: 'Smallest detectable value difference',
    unit: '%',
    lowerIsBetter: true,
    normativeRange: { lower: 1, upper: 5 },
  },
  {
    id: 'V2',
    name: 'Range',
    definition: 'Ratio of perceived to actual value range',
    unit: '%',
    lowerIsBetter: false,
    normativeRange: { lower: 70, upper: 100 },
  },
  {
    id: 'V3',
    name: 'Contrast',
    definition: 'Simultaneous contrast susceptibility',
    unit: '%',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 20 },
  },
  {
    id: 'V4',
    name: 'Adaptation',
    definition: 'Adaptation level shift after bright/dark field',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 3 },
  },
  {
    id: 'V5',
    name: 'Constancy',
    definition: 'Lightness constancy error under illumination change',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 2 },
  },
  {
    id: 'V6',
    name: 'Mach',
    definition: 'Mach band perception at value boundaries',
    unit: '%',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 50 },
  },
  {
    id: 'V7',
    name: 'Ordering',
    definition: 'Accuracy sorting values from light to dark',
    unit: '%',
    lowerIsBetter: false,
    normativeRange: { lower: 90, upper: 100 },
  },
  {
    id: 'V8',
    name: 'Matching',
    definition: 'Error matching a tone to a value scale',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 1 },
  },
  {
    id: 'V9',
    name: 'Context',
    definition: 'Context interference (texture/detail) on value judgment',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 2 },
  },
  {
    id: 'V10',
    name: 'Memory',
    definition: 'Value memory decay after delay',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 1 },
  },
  {
    id: 'V11',
    name: 'Background',
    definition: 'Background dependence of value judgment',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 1 },
  },
  {
    id: 'V12',
    name: 'Colour',
    definition: 'Colour-to-value translation error',
    unit: 'steps',
    lowerIsBetter: true,
    normativeRange: { lower: 0, upper: 2 },
  },
];