import type { Variable } from '@kata/core';

export const P1_VARIABLES: Variable[] = [
  {
    id: 'V1',
    name: 'Vertical deviation',
    definition: 'Judge the deviation of a line from true vertical',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 0.5, upper: 5 },
  },
  {
    id: 'V2',
    name: 'Horizontal deviation',
    definition: 'Judge the deviation of a line from true horizontal',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 0.5, upper: 5 },
  },
  {
    id: 'V3',
    name: 'Line difference',
    definition: 'Judge the angle between two lines',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 1, upper: 10 },
  },
  {
    id: 'V4',
    name: 'Direction',
    definition: 'Judge which way a line tilts (left or right)',
    unit: 'binary',
    lowerIsBetter: false,
    normativeRange: { lower: 90, upper: 100 },
  },
  {
    id: 'V5',
    name: 'Reference ID',
    definition: 'Identify the reference line in a scene',
    unit: 'binary',
    lowerIsBetter: false,
    normativeRange: { lower: 80, upper: 100 },
  },
  {
    id: 'V6',
    name: 'Angle magnitude',
    definition: 'Classify angles as acute, right, obtuse, reflex',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 5, upper: 15 },
  },
  {
    id: 'V7',
    name: 'Angle context',
    definition: 'Judge angle correctly despite distracting context',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 2, upper: 8 },
  },
  {
    id: 'V8',
    name: 'Angle memory',
    definition: 'Recall angle after a delay',
    unit: 'seconds',
    lowerIsBetter: false,
    normativeRange: { lower: 3, upper: 10 },
  },
  {
    id: 'V9',
    name: 'Angle transfer',
    definition: 'Judge the same angle at different scales',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 2, upper: 8 },
  },
  {
    id: 'V10',
    name: 'Angle symmetry',
    definition: 'Detect symmetry in a shape',
    unit: 'degrees',
    lowerIsBetter: true,
    normativeRange: { lower: 1, upper: 5 },
  },
];